name = "NET"
uuid = "73efcf44-39b4-4eda-bc9f-8ba3304d6b60"
authors = ["Emre Dayangaç"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
